[package]
name = "thms"
version = "0.1.0"
entrypoint = "thm-envs.typ"
authors = ["Fr4nk1inCs"]
license = "MIT"
description = "Typreset is a collection of typst presets for my daily writing. And thms is part of it."
repository = "https://github.com/Fr4nk1inCs/typreset/tree/master"