[package]
name = "svg-emoji"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Po' Lazarus"]
license = "MIT"
description = "Working emoji support through SVG files"
repository = "https://github.com/polazarus/typst-svg-emoji"